### ISSUE TITLE
No Search Results in Couchpotato, but can find many copies of movie manually on tracker

### ISSUE THREAD

**Issue by kingblah** [CouchPotato/CouchPotatoServer#6506]
### Steps to reproduce:
Searching for Movie "Gods of Egypt"
Quality setting: Tried "HD", "Best" and numerous others.
Searchers: Torrentz and Rarbg as public trackers as well as BitHDTV and AlphaRatio as private ones. I know for sure the movie is on BitHDTV as I've searched it manually and found more than three releases.
Have tried enabling and disabling "Always Search", to no avail.

### Information:
Version of CouchPotato: Latest release (no further updates available) (13a19423)
Running on: Ubuntu 14.04 

### Logs:
```
06-15 13:48:55 INFO
[core.media.movie.searcher] Search for Gods of Egypt in DVD-Rip ignoring ETA
06-15 13:49:42 INFO
[ie.providers.info.omdbapi] Found: Gods of Egypt (2016)
06-15 13:49:42 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 720p ignoring ETA
06-15 13:49:42 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 1080p ignoring ETA
06-15 13:49:43 INFO
[core.media.movie.searcher] Search for Gods of Egypt in BR-Rip ignoring ETA
06-15 13:49:43 INFO
[core.media.movie.searcher] Search for Gods of Egypt in DVD-Rip ignoring ETA
06-15 13:55:23 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 1080p ignoring ETA
06-15 13:55:23 INFO
[hpotato.core.plugins.base] Opening url: get https://www.bit-hdtv.com/torrents.php?&search=Gods+of+Egypt+2016&cat=7, data: []
06-15 13:55:23 INFO
[hpotato.core.plugins.base] Opening url: get https://alpharatio.cc/torrents.php?action=advanced&searchstr=Gods+of+Egypt+2016&scene=&filter_cat[7]=1, data: []
06-15 13:55:25 INFO
[hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22gods+of+egypt+2016%22%20size%204000m%20-%2020000m%20seed%20%3E%209, data: []
06-15 13:55:25 INFO
[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=m7v3tzuo20&mode=search&search_imdb=tt2404233&min_seeders=8&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: []
06-15 13:55:25 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 720p ignoring ETA
06-15 13:55:25 INFO
[hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22gods+of+egypt+2016%22%20size%203000m%20-%2010000m%20seed%20%3E%209, data: []
06-15 13:56:39 INFO
[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt2404233?api_key=xxx&append_to_response=alternative_titles, data: []
06-15 13:56:39 INFO
[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2404233/?ignore=1, data: []
06-15 13:56:39 INFO
[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2404233, data: []
06-15 13:56:39 INFO
[ie.providers.info.omdbapi] Found: Gods of Egypt (2016)
06-15 13:56:40 INFO
[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt2404233/, data: []
06-15 13:56:40 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 1080p ignoring ETA
06-15 13:56:40 INFO
[core.media.movie.searcher] Search for Gods of Egypt in 720p ignoring ETA
```

**Comment by CouchPotatoBot** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Fill in all the dots. They're there for a reason
- [ ] Post logs, either inline (for smaller logs) or using [Pastebin](http://pastebin.com/)
- [ ] Post full version information

Please make sure you also read [contribution guide](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues) and followed all the steps. 
Make the title describe your issue. Having "CP not working" or "I get this bug" for 100 issues, isn't really helpful. My master will close issues if there isn't enough information. On a good day he will tag the issue on close with the reason (like `can't reproduce`), but usually he won't, the lazy asshat.

Sometimes my master seems like a grumpy cat and responds with short answers. This isn't (always) because he hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let him know. Maybe he can teach me his awesome ways.

Thanks!

**Comment by lersince1991** [comment]
Same, I have had this problem for nearly a year and on every film. So couchpotato has been useless for a long time for me, same story on all macs I have tried it on including new installs from fresh OS....

**Comment by blade316** [comment]
@kingblah @lersince1991 Can you open those URL's manually in your browser and get to the torrent file?

**Comment by kingblah** [comment]
@blade316 That's correct - just tried opening the URLs manually and I'm getting the same results (less a couple) as I would by searching. Instead, couch potato seems to "give up" - I get the square-rotating animation on the movie for a few seconds and then nothing.

**Comment by blade316** [comment]
@kingblah sorry just to confirm, when you load those URLs in your browser you CAN get to the actually torrent files? or you cant?

Also can you please include some screenshots of your searcher settings, make sure its showing the advanced options.
