### ISSUE TITLE
ERROR cannot download from any Torrent tracker

### ISSUE THREAD

**Issue by juandeargentina** [CouchPotato/CouchPotatoServer#6672]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: Batman vs Superman
Quality of the movie being searched: HD 1080p
Providers I use: RARBG y ThePirateBay
Version of CouchPotato: desktop: 3.0.1
Running on: Windows 10

### Logs:
```
07-31 23:32:47 ERROR [ato.core._base.downloader] Failed converting magnet url to torrent: 5FA85EF49FDF6F63809FBB3838E6552D5C4D6C2D 
```

**Comment by CouchPotatoBot** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Fill in all the dots. They're there for a reason
- [x] Post logs, either inline (for smaller logs) or using [Pastebin](http://pastebin.com/)
- [x] Please wrap inline logs inside ``` for readability
- [ ] Enabled debug logging in Settings > Advanced (restart CP, be sure to disable after the bug is fixed)
- [x] Post full version information

Please make sure you also read [contribution guide](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues) and followed all the steps. 
Make the title describe your issue. Having "CP not working" or "I get this bug" for 100 issues, isn't really helpful. My master will close issues if there isn't enough information. On a good day he will tag the issue on close with the reason (like `can't reproduce`), but usually he won't, the lazy asshat.

Sometimes my master seems like a grumpy cat and responds with short answers. This isn't (always) because he hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let him know. Maybe he can teach me his awesome ways.

Thanks!

**Comment by juandeargentina** [comment]
Here you go....

08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to Rarbg
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to Yify
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to NZBClub
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to SceneAccess
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to KickAssTorrents
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to ILoveTorrents
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to TorrentShack
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to PassThePopcorn
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to HDAccess
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to OMGWTFNZBs
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to SceneTime
08-01 00:16:18
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:C77992C3A29AB456F66228BBF1C92C31BA49753F&dn=Batman+v+Superman+Dawn+of+Justice+2016+Extended+1080p+BluRay+AC3+x264+ETRG&tr=udp%3A%2F%2Ftracker.openbittorrent.com%2Fannounce doesn't belong to TorrentBytes
08-01 00:16:18
DEBUG
[.downloaders.qbittorrent_] Sending "Batman v Superman Dawn of Justice 2016 Extended 1080p BluRay AC3 x264 ETRG" to qBittorrent.
08-01 00:16:18
INFO
[hpotato.core.plugins.base] Opening url: get https://torcache.net/torrent/C77992C3A29AB456F66228BBF1C92C31BA49753F.torrent, data: []
08-01 00:16:19
DEBUG
[ato.core._base.downloader] Torrent hash "C77992C3A29AB456F66228BBF1C92C31BA49753F" wasn't found on: https://torcache.net/torrent/%s.torrent
08-01 00:16:19
ERROR
[ato.core._base.downloader] Failed converting magnet url to torrent: C77992C3A29AB456F66228BBF1C92C31BA49753F
08-01 00:16:19
INFO
[tato.core.plugins.release] Tried to download, but the "torrent_magnet" downloader gave an error
08-01 00:16:19
DEBUG
[o.core.notifications.core] Getting messages with id: 409270a9-1947-4775-b166-ed26d2a4c667
08-01 00:16:19
DEBUG
[o.core.notifications.core] Returning for 409270a9-1947-4775-b166-ed26d2a4c667 0 messages
08-01 00:16:29
DEBUG
[o.core.notifications.core] Cleaning messages
08-01 00:16:29
DEBUG
[o.core.notifications.core] Done cleaning messages
08-01 00:16:44
DEBUG
[o.core.notifications.core] Cleaning messages
08-01 00:16:44
DEBUG
[o.core.notifications.core] Done cleaning messages

**Comment by hjdr4** [comment]
Hello,

I just have the same bug.
Torrent cache is broken, and I don't get why we should use it.

I just patched core/downloaders/qbittorent_.py download method (from master branch) to use the magnet link, as qBittorrent supports:
http://pastebin.com/6Fm35Mdn

Hope this helps

**Comment by juandeargentina** [comment]
Hi hjdr4....
I just paste your code....and no luck. 

This is the response log before replace qbittorrent_.py 
08-07 23:40:20
DEBUG
[hpotato.core.plugins.base] Getting cache imdb.chart_display_rentals
08-07 23:40:20
DEBUG
[hpotato.core.plugins.base] Getting cache imdb.chart_display_boxoffice
08-07 23:40:36
DEBUG
[o.core.notifications.core] Notifying frontend
08-07 23:40:36
DEBUG
[o.core.notifications.core] Done notifying frontend
08-07 23:40:36
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:dead5ac505c5b1f223ecba6574c7b189096bc3ca&dn=Zootopia.2016.1080p.BluRay.x264-SPARKS&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce doesn't belong to ThePirateBay
08-07 23:40:36
DEBUG
[edia._base.providers.base] Url magnet:?xt=urn:btih:dead5ac505c5b1f223ecba6574c7b189096bc3ca&dn=Zootopia.2016.1080p.BluRay.x264-SPARKS&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce doesn't belong to BiTHDTV
08-07 23:40:36
DEBUG
[.downloaders.qbittorrent_] Sending "Zootopia.2016.1080p.BluRay.x264-SPARKS (2016)  SPARKS  1080p  x264  292 seeders" to qBittorrent.
08-07 23:40:36
ERROR
[   couchpotato.core.event] Error in event "download", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\server\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\server\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\_base\downloader\main.py", line 72, in _download
  File "C:\Users\server\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\downloaders\qbittorrent_.py", line 70, in download
  File "C:\Users\server\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\downloaders\qbittorrent_.py", line 35, in connect
AttributeError: 'QBittorrentClient' object has no attribute 'login'
encoding=cp1252 debug=True args=['--quiet'] app_dir=C:\Users\server\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32 data_dir=C:\Users\server\AppData\Roaming\CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x3839b48> > options=Namespace(config_file='C:\\Users\\server\\AppData\\Roaming\\CouchPotato\\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\\Users\\server\\AppData\\Roaming\\CouchPotato\\couchpotato.pid', quiet=True) 
08-07 23:40:36
DEBUG
[aders.qbittorrent_ - Copy] Sending "Zootopia.2016.1080p.BluRay.x264-SPARKS (2016)  SPARKS  1080p  x264  292 seeders" to qBittorrent.
08-07 23:40:36
INFO
[hpotato.core.plugins.base] Opening url: get https://torcache.net/torrent/DEAD5AC505C5B1F223ECBA6574C7B189096BC3CA.torrent, data: []
08-07 23:40:36
DEBUG
[ato.core._base.downloader] Torrent hash "DEAD5AC505C5B1F223ECBA6574C7B189096BC3CA" wasn't found on: https://torcache.net/torrent/%s.torrent
08-07 23:40:36
ERROR
[ato.core._base.downloader] Failed converting magnet url to torrent: DEAD5AC505C5B1F223ECBA6574C7B189096BC3CA
08-07 23:40:36
INFO
[tato.core.plugins.release] Tried to download, but the "torrent_magnet" downloader gave an error
08-07 23:40:38
DEBUG
[o.core.notifications.core] Getting messages with id: d075855c-cac3-449a-9e24-6d0e1f1ff112
08-07 23:40:38
DEBUG
[o.core.notifications.core] Returning for d075855c-cac3-449a-9e24-6d0e1f1ff112 0 messages
08-07 23:40:38
DEBUG
[o.core.notifications.core] Cleaning messages
08-07 23:40:38
DEBUG
[o.core.notifications.core] Done cleaning messages

Thanks anyway for your help...
