### ISSUE TITLE
IPT tracker issues, again.

### ISSUE THREAD

**Issue by AtomArne** [CouchPotato/CouchPotatoServer#6815]
### Steps to reproduce:
Just add the tracker.

Notes:
1. Double checked credentials.
2. All other providers work.

### Information:
Movie(s) I have this with: Every movie on IPT
Quality of the movie being searched: From 1080p to 720p.
Providers I use: IPT
Version of CouchPotato: desktop: 3.0.1
Running on: Windows 10

### Logs:
```
09-01 09:27:06 ERROR [hpotato.core.plugins.base] Failed opening url in IPTorrents: https://iptorrents.eu/inbox.php Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://iptorrents.eu/inbox.php
 
```

Posted a message on IPT forum asked if they changed anything.

**Comment by CouchPotatoBot** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Fill in all the dots. They're there for a reason
- [x] Post logs, either inline (for smaller logs) or using [Pastebin](http://pastebin.com/)
- [x] Please wrap inline logs inside ``` for readability
- [ ] Enabled debug logging in Settings > Advanced (restart CP, be sure to disable after the bug is fixed)
- [x] Post full version information

Please make sure you also read [contribution guide](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues) and followed all the steps. 
Make the title describe your issue. Having "CP not working" or "I get this bug" for 100 issues, isn't really helpful. My master will close issues if there isn't enough information. On a good day he will tag the issue on close with the reason (like `can't reproduce`), but usually he won't, the lazy asshat.

Sometimes my master seems like a grumpy cat and responds with short answers. This isn't (always) because he hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let him know. Maybe he can teach me his awesome ways.

Thanks!

**Comment by crypticedge** [comment]
Switch to develop branch. The fix for it is in there.

**Comment by AtomArne** [comment]
develop branch?

**Comment by crypticedge** [comment]
Correct. I use a synology and it has me set it during install of the synology-custom package, since I was on a fresh install anyway that only had configs setup, nothing more I just copied my config and then reinstalled on develop branch, then reimported my config. You can also use git to change it, but I'm less familiar with that.

**Comment by AtomArne** [comment]
Hey Cryptic.

Im sorry, this branch. How do i choose this? Do i need to reinstall CP?
Im running it on a Windows 10 Machine

**Comment by crypticedge** [comment]
This was the instructions for doing it on synology. Basically, back up your database, then reinstall with develop as your branch then reload the DB.

https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository



On Tue, Sep 6, 2016 at 3:00 PM -0400, "AtomArne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Cryptic.

Im sorry, this branch. How do i choose this? Do i need to reinstall CP?
Im running it on a Windows 10 Machine

**Comment by AtomArne** [comment]
Hey thanks bro.

But, you are aware that this is an "Couch Potato" issue? My SickRage is running just fine :)

**Comment by crypticedge** [comment]
Holy crap I didn't read the link I sent. I still had to do the same steps to fix (without the backup it details) but I'm sorry I missed that. I redid my whole NAS this weekend so that part bled in

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Sep 6, 2016 at 4:08 PM -0400, "AtomArne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey thanks bro.

But, you are aware that this is an "Couch Potato" issue? My SickRage is running just fine :)

**Comment by AtomArne** [comment]
Hey no worrys.

The only problem now is that i am back at square one :(
