### ISSUE TITLE
Getting this error with specific tracker

### ISSUE THREAD

**Issue by Titte95** [CouchPotato/CouchPotatoServer#7114]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(CouchPotato:CouchPotatoServer master) d7238913 (2016-11-07 20:37:29)
Running on: ...

### Logs:
```
11-08 17:11:47 ERROR [edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/home/titte95/.couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/home/titte95/.couchpotato/couchpotato/core/plugins/base.py", line 227, in urlopen
    response.raise_for_status()
  File "/home/titte95/.couchpotato/libs/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://localhost:9117/jackett/dl/danishbits/XXXXXXXXXXX?path=aHR0cHM6Ly9kYW5pc2hiaXRzLm9yZy90b3JyZW50cy5waHAvV2FyLkRvZ3MuMjAxNi5ES1N1YnMuMTA4MHAuQmx1UmF5LngyNjQtVU5pVEFpTC50b3JyZW50Lz9hY3Rpb249ZG93bmxvYWQmYXV0aGtleT0mdG9ycmVudF9wYXNzPSZpZD01&file=War.Dogs.2016.DKSubs.1080p.BluRay.x264-UNiTAiL.torrent
 
```

**Comment by CouchPotatoBot** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Fill in all the dots. They're there for a reason
- [x] Post logs, either inline (for smaller logs) or using [Pastebin](http://pastebin.com/)
- [x] Please wrap inline logs inside ``` for readability
- [ ] Enabled debug logging in Settings > Advanced (restart CP, be sure to disable after the bug is fixed)
- [ ] Post full version information

Please make sure you also read [contribution guide](https://github.com/RuudBurger/CouchPotatoServer/blob/develop/contributing.md#issues) and followed all the steps. 
Make the title describe your issue. Having "CP not working" or "I get this bug" for 100 issues, isn't really helpful. My master will close issues if there isn't enough information. On a good day he will tag the issue on close with the reason (like `can't reproduce`), but usually he won't, the lazy asshat.

Sometimes my master seems like a grumpy cat and responds with short answers. This isn't (always) because he hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let him know. Maybe he can teach me his awesome ways.

Thanks!
